VRM.Presentation/Models/RoleViewModel.cs
namespace VRM.Presentation.Models
{
    using System.ComponentModel.DataAnnotations;
    public class RoleViewModel
    {
        public string Id { get; set; }
        [Display(Name = "Role Name")]
        public string RoleName { get; set; }
    }
}

VRM.Presentation/Controllers/RoleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VRM.DAL.Data;
using VRM.DAL.Models;
using VRM.Presentation.Models;

namespace VRM.Presentation.Controllers
{
    public class RoleController : Controller
    { 
            private readonly RoleManager<AppRole> roleManager;

            public RoleController(RoleManager<AppRole> roleManager)
            {
                this.roleManager = roleManager;
            }
        [HttpGet]
        public IActionResult Index()
        {
            List<AppRoleListViewModel> model = new List<AppRoleListViewModel>();
            model = roleManager.Roles.Select(r => new AppRoleListViewModel
            {
                RoleName = r.Name,
                Id = r.Id,
            }).ToList();
            bool isAdmin = User
                .Identities.FirstOrDefault(i => i.AuthenticationType == "Identity.Application")
                .Claims.Any(i => i.Value == "Admin");
            ViewBag.isAdmin = isAdmin;
            return View(model);
        }
        public async Task<IActionResult> CreateOrEdit(string id)
        {
            RoleViewModel model = new RoleViewModel();
            if (!String.IsNullOrEmpty(id))
            {
                AppRole applicationRole = await roleManager.FindByIdAsync(id);
                if (applicationRole != null)
                {
                    model.Id = applicationRole.Id;
                    model.RoleName = applicationRole.Name;
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrEdit(string id, RoleViewModel model)
        {

            bool isExist = !String.IsNullOrEmpty(id);
            AppRole applicationRole = isExist ? await roleManager.FindByIdAsync(id) :
           new AppRole
           {

           };
            applicationRole.Name = model.RoleName;
            IdentityResult roleRuslt = isExist ? await roleManager.UpdateAsync(applicationRole)
                                                : await roleManager.CreateAsync(applicationRole);
            if (roleRuslt.Succeeded)
            {
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> AddEditApplicationRole(string id)
        {
            RoleViewModel model = new RoleViewModel();
            if (!String.IsNullOrEmpty(id))
            {
                AppRole applicationRole = await roleManager.FindByIdAsync(id);
                if (applicationRole != null)
                {
                    model.Id = applicationRole.Id;
                    model.RoleName = applicationRole.Name;
                }
            }
            return PartialView("_AddEditApplicationRole", model);
        }
        [HttpPost]
        public async Task<IActionResult> AddEditApplicationRole(string id, RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                bool isExist = !String.IsNullOrEmpty(id);
                AppRole applicationRole = isExist ? await roleManager.FindByIdAsync(id) :
               new AppRole
               {
               };
                applicationRole.Name = model.RoleName;
                IdentityResult roleRuslt = isExist ? await roleManager.UpdateAsync(applicationRole)
                                                    : await roleManager.CreateAsync(applicationRole);
                if (roleRuslt.Succeeded)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }
    }
}

VRM.Presentation/Views/Role/Configure.cshtml
@model IEnumerable<AppRoleListViewModel>
  
@{
    ViewData["Title"] = "Roles";
}

<div class="card shadow mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered align-content-center" id="Datatable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.RoleName)
                        </th>
                        <th class="dontNeedFilter">
                            Actions
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var role in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(r => role.RoleName)
                            </td>
                            <td>
                                <div>
                                    <a asp-controller="Role" asp-action="CreateOrEdit" asp-route-Id="@role.Id"><br>Edit</a>
                                    <a asp-controller="Role" asp-action="Delete" asp-route-Id="@role.Id"><br>Delete</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts{
<link href="~/lib/datatables/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
<script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
<script src="~/js/roleDatatable.js"></script>
}

VRM.Presentation/Views/Role/CreateOrEdit.cshtml
@model RoleViewModel  
  
@{
    if (@Model.RoleName == null)
    {
        ViewData["Title"] = "Add Role";
    }
}

<form method="post">
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <label asp-for="RoleName" class="control-label"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        <button asp-controller="Role" asp-action="Configure" class="btn btn-secondary">Cancel</button>  
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.5/js/standalone/selectize.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.13.5/css/selectize.bootstrap4.min.css"/>
}

VRM.Presentation/Views/Role/Index.cshtml
@model IEnumerable<AppRoleListViewModel>  
@using VRM.DAL.Models 
  
<div class="top-buffer"></div>  
<div class="panel panel-primary">  
    <div class="panel-heading panel-head">Application Roles</div>  
    <div class="panel-body">  
        <div class="btn-group">  
            <a id="createRoleModal" data-toggle="modal" asp-action="CreateOrEdit" data-target="#modal-action-application-role" class="btn btn-primary">  
                <i class="glyphicon glyphicon-plus"></i>  Add Role  
            </a>  
        </div>  
        <div class="top-buffer"></div>  
        <table class="table table-bordered table-striped table-condensed">  
            <thead>  
                <tr>  
                    <th>Name</th>                  
                    <th>Action</th>  
                </tr>  
            </thead>  
            <tbody>  
                @foreach (var item in Model)  
                {  
                    <tr>  
                        <td>@item.RoleName</td>                                                
                        <td>                              
                            <a id="addEditApplicationRoleModal" data-toggle="modal" asp-action="CreateOrEdit" asp-route-id="@item.Id" data-target="#modal-action-application-role"  
                               class="btn btn-info">  
                                <i class="glyphicon glyphicon-pencil"></i>  Edit  
                            </a>  
                            @if (item.NumberOfUsers == 0)  
                            {  
                            <a id="deleteApplicationRoleModal" data-toggle="modal" asp-action="Delete" asp-route-id="@item.Id" data-target="#modal-action-application-role" class="btn btn-danger">  
                                <i class="glyphicon glyphicon-trash"></i>  Delete  
                            </a>  
                            }  
                        </td>  
                    </tr>  
                }  
            </tbody>  
        </table>  
    </div>  
</div>  
  
@*@Html.Partial("_Modal", new BootstrapModel { ID = "modal-action-application-role", AreaLabeledId = "modal-action-application-role-label", Size = ModalSize.Medium })  *@
  
@section scripts  
{  
    <script src="~/js/application-role-index.js" asp-append-version="true"></script>  
}   

VRM.Presentation/Views/Role/_AddEditApplicationRole.cshtml
@*@model RoleViewModel  
@using VRM.DAL.Models 
  
<form asp-action="AddEditApplicationRole" role="form">  
    @await Html.PartialAsync("_ModalHeader", new ModalHeader { Heading =$"{(String.IsNullOrEmpty(Model.Id)? "Add" : "Edit")} Application Role"  })  
    <div class="modal-body form-horizontal">  
        <div class="row">  
            <div class="form-group">  
                <label asp-for="RoleName" class="col-lg-3 col-sm-3 control-label"></label>  
                <div class="col-lg-6">  
                    <input asp-for="RoleName" class="form-control" />  
                </div>  
            </div>  
            <div class="form-group">  
                <label asp-for="Description" class="col-lg-3 col-sm-3 control-label"></label>  
                <div class="col-lg-6">  
                    <input asp-for="Description" class="form-control" />  
                </div>  
            </div>  
        </div>  
    </div>  
    @await Html.PartialAsync("_ModalFooter", new ModalFooter { })  
</form>   *@